export default {
  "species": [
    "Dog",
    "Cat",
    "Rabbit",
    "Hamster",
    "Guinea pig",
    "Mouse",
    "Rat",
    "Gerbil",
    "Chinchilla",
    "Ferret",
    "Hedgehog",
    "Sugar glider",
    "Bird",
    "Parrot",
    "Lovebird",
    "Cockatiel",
    "Budgie",
    "Canary",
    "Finch",
    "Chicken",
    "Duck",
    "Goose",
    "Turkey",
    "Pigeon",
    "Quail",
    "Fish",
    "Goldfish",
    "Betta",
    "Turtle",
    "Tortoise",
    "Lizard",
    "Gecko",
    "Iguana",
    "Snake",
    "Frog",
    "Toad",
    "Axolotl",
    "Horse",
    "Pony",
    "Donkey",
    "Goat",
    "Sheep",
    "Pig",
    "Cow",
    "Carabao",
    "Monkey",
    "Other"
  ],
  "breeds": {
    "Dog": [
      "Affenpinscher",
      "Afghan Hound",
      "Airedale Terrier",
      "Akita",
      "Alaskan Malamute",
      "American Bully",
      "American Eskimo Dog",
      "American Foxhound",
      "American Staffordshire Terrier",
      "Australian Cattle Dog",
      "Australian Shepherd",
      "Basenji",
      "Basset Hound",
      "Beagle",
      "Belgian Malinois",
      "Belgian Sheepdog",
      "Bernese Mountain Dog",
      "Bichon Frise",
      "Bloodhound",
      "Border Collie",
      "Border Terrier",
      "Borzoi",
      "Boston Terrier",
      "Boxer",
      "Brittany",
      "Brussels Griffon",
      "Bull Terrier",
      "Bulldog",
      "Bullmastiff",
      "Cairn Terrier",
      "Cane Corso",
      "Cavalier King Charles Spaniel",
      "Chihuahua",
      "Chinese Crested",
      "Chow Chow",
      "Cocker Spaniel",
      "Collie",
      "Corgi",
      "Dachshund",
      "Dalmatian",
      "Doberman Pinscher",
      "English Cocker Spaniel",
      "English Setter",
      "English Springer Spaniel",
      "French Bulldog",
      "German Pinscher",
      "German Shepherd",
      "German Shorthaired Pointer",
      "Golden Retriever",
      "Great Dane",
      "Great Pyrenees",
      "Greyhound",
      "Havanese",
      "Irish Setter",
      "Irish Wolfhound",
      "Italian Greyhound",
      "Jack Russell Terrier",
      "Japanese Spitz",
      "Keeshond",
      "Labrador Retriever",
      "Lhasa Apso",
      "Maltese",
      "Mastiff",
      "Miniature Pinscher",
      "Miniature Schnauzer",
      "Mixed Breed",
      "Newfoundland",
      "Norwegian Elkhound",
      "Old English Sheepdog",
      "Papillon",
      "Pekingese",
      "Pembroke Welsh Corgi",
      "Pomeranian",
      "Poodle",
      "Portuguese Water Dog",
      "Pug",
      "Rottweiler",
      "Saint Bernard",
      "Samoyed",
      "Schnauzer",
      "Scottish Terrier",
      "Shar Pei",
      "Shetland Sheepdog",
      "Shiba Inu",
      "Shih Tzu",
      "Siberian Husky",
      "Staffordshire Bull Terrier",
      "Toy Poodle",
      "Vizsla",
      "Weimaraner",
      "West Highland White Terrier",
      "Whippet",
      "Yorkshire Terrier",
      "Aspin (Asong Pinoy)"
    ],
    "Cat": [
      "Abyssinian",
      "American Bobtail",
      "American Curl",
      "American Shorthair",
      "American Wirehair",
      "Balinese",
      "Bengal",
      "Birman",
      "Bombay",
      "British Longhair",
      "British Shorthair",
      "Burmese",
      "Burmilla",
      "Chartreux",
      "Cornish Rex",
      "Devon Rex",
      "Domestic Longhair",
      "Domestic Shorthair",
      "Egyptian Mau",
      "Exotic Shorthair",
      "Havana Brown",
      "Himalayan",
      "Japanese Bobtail",
      "Khao Manee",
      "Korat",
      "LaPerm",
      "Maine Coon",
      "Manx",
      "Munchkin",
      "Norwegian Forest Cat",
      "Ocicat",
      "Oriental Longhair",
      "Oriental Shorthair",
      "Persian",
      "Peterbald",
      "Pixiebob",
      "Ragamuffin",
      "Ragdoll",
      "Russian Blue",
      "Savannah",
      "Scottish Fold",
      "Selkirk Rex",
      "Siamese",
      "Siberian",
      "Singapura",
      "Snowshoe",
      "Somali",
      "Sphynx",
      "Tonkinese",
      "Turkish Angora",
      "Turkish Van",
      "Mixed Breed",
      "Puspin (Pusang Pinoy)"
    ],
    "Rabbit": [
      "American",
      "American Chinchilla",
      "American Fuzzy Lop",
      "Belgian Hare",
      "Californian",
      "Checkered Giant",
      "Dutch",
      "Dwarf Hotot",
      "English Angora",
      "English Lop",
      "English Spot",
      "Flemish Giant",
      "Florida White",
      "French Angora",
      "French Lop",
      "Harlequin",
      "Havana",
      "Holland Lop",
      "Jersey Wooly",
      "Lionhead",
      "Mini Lop",
      "Mini Rex",
      "Netherland Dwarf",
      "New Zealand",
      "Polish",
      "Rex",
      "Satin",
      "Silver Fox",
      "Mixed Breed"
    ],
    "Hamster": [
      "Syrian",
      "Campbell???s Dwarf",
      "Winter White Dwarf",
      "Roborovski Dwarf",
      "Chinese Hamster"
    ],
    "Guinea pig": [
      "Abyssinian",
      "American",
      "Coronet",
      "Himalayan",
      "Lunkarya",
      "Merino",
      "Peruvian",
      "Rex",
      "Sheba",
      "Silkie",
      "Skinny Pig",
      "Teddy",
      "Texel",
      "White Crested"
    ],
    "Mouse": [
      "Fancy Mouse",
      "Satin Mouse",
      "Long-haired Mouse",
      "Hairless Mouse"
    ],
    "Rat": [
      "Standard",
      "Dumbo",
      "Rex",
      "Double Rex",
      "Hairless",
      "Satin",
      "Tailless"
    ],
    "Gerbil": [
      "Mongolian Gerbil",
      "Fat-tailed Gerbil",
      "Pallid Gerbil",
      "Shaw???s Jird"
    ],
    "Chinchilla": [
      "Standard Gray",
      "Beige",
      "Black Velvet",
      "Ebony",
      "White Mosaic",
      "Violet",
      "Sapphire"
    ],
    "Ferret": [
      "Albino",
      "Black Sable",
      "Champagne",
      "Chocolate",
      "Cinnamon",
      "Dark-eyed White",
      "Sable",
      "Silver"
    ],
    "Hedgehog": [
      "African Pygmy",
      "Algerian",
      "Egyptian Long-eared",
      "Indian Long-eared"
    ],
    "Sugar glider": [
      "Classic Gray",
      "Leucistic",
      "Mosaic",
      "Platinum",
      "White Face",
      "Creamino"
    ],
    "Bird": [
      "African Grey",
      "Budgerigar",
      "Canary",
      "Cockatiel",
      "Cockatoo",
      "Conure",
      "Dove",
      "Eclectus",
      "Finch",
      "Lovebird",
      "Macaw",
      "Mynah",
      "Parrotlet",
      "Pigeon"
    ],
    "Parrot": [
      "African Grey",
      "Amazon",
      "Caique",
      "Cockatoo",
      "Conure",
      "Eclectus",
      "Indian Ringneck",
      "Lorikeet",
      "Macaw",
      "Meyer???s Parrot",
      "Parrotlet",
      "Quaker Parrot",
      "Senegal Parrot"
    ],
    "Lovebird": [
      "Fischer???s",
      "Lilian???s",
      "Masked",
      "Peach-faced",
      "Red-headed",
      "Yellow-collared"
    ],
    "Cockatiel": [
      "Normal Gray",
      "Cinnamon",
      "Fallow",
      "Lutino",
      "Pearl",
      "Pied",
      "Silver",
      "Whiteface"
    ],
    "Budgie": [
      "American Budgie",
      "English Budgie",
      "Exhibition Budgie"
    ],
    "Canary": [
      "American Singer",
      "Belgian Fancy",
      "Border Fancy",
      "Gloster",
      "Norwich",
      "Red Factor",
      "Yorkshire"
    ],
    "Finch": [
      "Gouldian",
      "Java Sparrow",
      "Owl Finch",
      "Society Finch",
      "Star Finch",
      "Zebra Finch"
    ],
    "Chicken": [
      "Ameraucana",
      "Australorp",
      "Ayam Cemani",
      "Bantam",
      "Barred Plymouth Rock",
      "Brahma",
      "Cochin",
      "Cornish",
      "Faverolles",
      "Jersey Giant",
      "Leghorn",
      "Marans",
      "New Hampshire Red",
      "Orpington",
      "Plymouth Rock",
      "Polish",
      "Rhode Island Red",
      "Silkie",
      "Sussex",
      "Banaba",
      "Bolinao",
      "Camarines",
      "Darag",
      "Joloanon",
      "Paraoakan"
    ],
    "Duck": [
      "Aylesbury",
      "Cayuga",
      "Indian Runner",
      "Khaki Campbell",
      "Mallard",
      "Muscovy",
      "Pekin",
      "Rouen",
      "Swedish Blue"
    ],
    "Goose": [
      "African",
      "American Buff",
      "Chinese",
      "Embden",
      "Pilgrim",
      "Sebastopol",
      "Toulouse"
    ],
    "Turkey": [
      "Beltsville Small White",
      "Black",
      "Blue Slate",
      "Bourbon Red",
      "Broad Breasted White",
      "Narragansett",
      "Royal Palm"
    ],
    "Pigeon": [
      "Fantail",
      "Homing Pigeon",
      "King",
      "Lahore",
      "Modena",
      "Roller",
      "Runt",
      "Tumbler"
    ],
    "Quail": [
      "Bobwhite",
      "Button Quail",
      "California Quail",
      "Coturnix",
      "Gambel???s Quail",
      "Japanese Quail"
    ],
    "Fish": [
      "Angelfish",
      "Barb",
      "Cichlid",
      "Corydoras",
      "Discus",
      "Gourami",
      "Guppy",
      "Koi",
      "Molly",
      "Oscar",
      "Platy",
      "Rainbowfish",
      "Rasbora",
      "Swordtail",
      "Tetra"
    ],
    "Goldfish": [
      "Black Moor",
      "Bubble Eye",
      "Celestial Eye",
      "Common",
      "Comet",
      "Fantail",
      "Lionhead",
      "Oranda",
      "Pearlscale",
      "Ranchu",
      "Ryukin",
      "Shubunkin",
      "Telescope Eye",
      "Veiltail"
    ],
    "Betta": [
      "Crowntail",
      "Delta Tail",
      "Double Tail",
      "Halfmoon",
      "Plakat",
      "Rosetail",
      "Spade Tail",
      "Veiltail"
    ],
    "Turtle": [
      "Box Turtle",
      "Map Turtle",
      "Mata Mata",
      "Musk Turtle",
      "Painted Turtle",
      "Red-eared Slider",
      "Softshell Turtle"
    ],
    "Tortoise": [
      "African Spurred",
      "Aldabra Giant",
      "Greek",
      "Hermann???s",
      "Indian Star",
      "Leopard",
      "Red-footed",
      "Russian"
    ],
    "Lizard": [
      "Bearded Dragon",
      "Blue-tongued Skink",
      "Chameleon",
      "Green Anole",
      "Monitor Lizard",
      "Skink",
      "Uromastyx"
    ],
    "Gecko": [
      "African Fat-tailed",
      "Crested",
      "Day Gecko",
      "Gargoyle",
      "Leachianus",
      "Leopard",
      "Tokay"
    ],
    "Iguana": [
      "Blue Iguana",
      "Desert Iguana",
      "Fiji Banded Iguana",
      "Green Iguana",
      "Rhinoceros Iguana"
    ],
    "Snake": [
      "Ball Python",
      "Boa Constrictor",
      "California Kingsnake",
      "Carpet Python",
      "Children???s Python",
      "Corn Snake",
      "Garter Snake",
      "Hognose Snake",
      "Kenyan Sand Boa",
      "Milk Snake",
      "Rat Snake"
    ],
    "Frog": [
      "African Bullfrog",
      "African Dwarf Frog",
      "Dart Frog",
      "Pacman Frog",
      "Tomato Frog",
      "Tree Frog"
    ],
    "Toad": [
      "American Toad",
      "Asian Common Toad",
      "Cane Toad",
      "Fire-bellied Toad",
      "Surinam Toad"
    ],
    "Axolotl": [
      "Wild Type",
      "Leucistic",
      "White Albino",
      "Golden Albino",
      "Melanoid",
      "Copper",
      "Mosaic"
    ],
    "Horse": [
      "American Paint Horse",
      "American Quarter Horse",
      "Andalusian",
      "Appaloosa",
      "Arabian",
      "Clydesdale",
      "Friesian",
      "Haflinger",
      "Hanoverian",
      "Morgan",
      "Mustang",
      "Percheron",
      "Shetland",
      "Shire",
      "Standardbred",
      "Thoroughbred",
      "Warmblood"
    ],
    "Pony": [
      "Connemara",
      "Dartmoor",
      "Fell Pony",
      "Hackney Pony",
      "New Forest Pony",
      "Shetland Pony",
      "Welsh Pony"
    ],
    "Donkey": [
      "American Mammoth Jackstock",
      "Andalusian",
      "Miniature Mediterranean",
      "Poitou",
      "Sicilian"
    ],
    "Goat": [
      "Alpine",
      "Anglo-Nubian",
      "Angora",
      "Boer",
      "Kiko",
      "LaMancha",
      "Nigerian Dwarf",
      "Pygmy",
      "Saanen",
      "Toggenburg",
      "Philippine Native"
    ],
    "Sheep": [
      "Corriedale",
      "Dorper",
      "Dorset",
      "Hampshire",
      "Katahdin",
      "Merino",
      "Rambouillet",
      "Suffolk"
    ],
    "Pig": [
      "Berkshire",
      "Duroc",
      "Hampshire",
      "Landrace",
      "Large White",
      "Pietrain",
      "Pot-bellied",
      "Philippine Native"
    ],
    "Cow": [
      "Angus",
      "Brahman",
      "Brown Swiss",
      "Charolais",
      "Guernsey",
      "Hereford",
      "Holstein Friesian",
      "Jersey",
      "Limousin",
      "Sahiwal",
      "Simmental",
      "Philippine Native"
    ],
    "Carabao": [
      "Philippine Carabao",
      "Murrah",
      "Nili-Ravi",
      "Swamp Buffalo",
      "Mediterranean Buffalo"
    ],
    "Monkey": [
      "Capuchin",
      "Macaque",
      "Marmoset",
      "Squirrel Monkey",
      "Tamarin"
    ]
  }
};
